internal/pkg/crawl/capture.go

This commit will ensure we are locally seenchecking first, then moving onto HQ if required and enabled.

Always use local seencheck first if enabled

---

cmd/cmd.go
cmd/utils.go
config/config.go
internal/pkg/crawl/crawl.go
internal/pkg/crawl/warc.go

We're adding an option to disable this due to potential memory issues.

feat: add option to disable local deduplication 

---

go.mod
go.sum
internal/pkg/crawl/crawl.go

Add support for error channel which gets logged to logWarning.

feat: update WARC to v0.8.7

---

.gitignore
cmd/utils.go
internal/pkg/utils/version.go

Per discussions, we wanted to have a better user-agent to better identify our crawler. This should provide that information.
Example: "Mozilla/5.0 (compatible; archive.org_bot +http://archive.org/details/archive.org_bot) Zeno/20821a0 warc/v0.8.28"

User-Agent improvements

---

cmd/cmd.go
cmd/utils.go
config/config.go
go.mod
internal/pkg/crawl/capture.go
internal/pkg/crawl/crawl.go
internal/pkg/frontier/seencheck.go

Redirect user-agent fix, local seencheck type fix, warc-dedup-size.

Various bug fixes

---

internal/pkg/crawl/assets.go
internal/pkg/crawl/capture.go
internal/pkg/crawl/sitespecific/telegram/telegram.go

Telegram need some specific work to be archived properly. This PR aim to add support for Telegram.

Add: Telegram support

---

cmd/utils.go
internal/pkg/crawl/api.go
internal/pkg/crawl/capture.go
internal/pkg/crawl/crawl.go
internal/pkg/crawl/finish.go
internal/pkg/crawl/worker.go

- Workers are now bound to a an operator-like structure, their state is visible and manipulated through that object
- Workers state is visible using API queries

Add state management for workers

---

cmd/utils.go
internal/pkg/log/file.go
internal/pkg/log/log.go
internal/pkg/log/rotate.go

Issue #70 resolved, will use this PR to improve code quality as well

fix: logfile declaration in log.go:New()

---

cmd/cmd.go
cmd/utils.go
config/config.go
internal/pkg/crawl/crawl.go
internal/pkg/crawl/utils.go

Closes #61
@CorentinB  Please note, I'm not proficient in Go, so feedback is welcomed and edit at will.

Allow crawl space threshold to be set on CLI, report space avail

---

internal/pkg/crawl/config.go
internal/pkg/utils/version.go

Fix commit hash in User Agent can't be calculated when not present

---

internal/pkg/queue/item.go

The time to load 10,000,000 URLs was reduced from 70s to 15s on my machine.
Printing progress for every line is expensive.

Optimize `get list` loading performance

---

internal/pkg/crawl/api.go
internal/pkg/crawl/crawl.go
internal/pkg/crawl/hq.go
internal/pkg/crawl/outlinks.go
internal/pkg/queue/dequeue.go
internal/pkg/queue/dequeue_test.go
internal/pkg/queue/enqueue.go
internal/pkg/queue/enqueue_test.go
internal/pkg/queue/index/manager.go
internal/pkg/queue/index/manager_test.go
internal/pkg/queue/index/recovery_test.go
internal/pkg/queue/index/wal.go
internal/pkg/queue/index/wal_test.go
internal/pkg/queue/metadata.go
internal/pkg/queue/queue.go
internal/pkg/queue/queue_test.go
internal/pkg/queue/stats.go

~~WIP~~ DONE
I'm a bit sleepy, I'll add the PR description hours later.

Improve WAL concurrency performance

---

cmd/get.go
config/config.go
internal/pkg/crawl/api.go
internal/pkg/crawl/config.go
internal/pkg/crawl/crawl.go
internal/pkg/crawl/hq.go
internal/pkg/crawl/outlinks.go
internal/pkg/queue/access_test.go
internal/pkg/queue/dequeue.go
internal/pkg/queue/dequeue_test.go
internal/pkg/queue/enqueue.go
internal/pkg/queue/enqueue_test.go
internal/pkg/queue/error.go
internal/pkg/queue/index/manager.go
internal/pkg/queue/index/manager_test.go
internal/pkg/queue/index/recovery_test.go
internal/pkg/queue/index/wal.go
internal/pkg/queue/index/wal_test.go
internal/pkg/queue/metadata.go
internal/pkg/queue/queue.go
internal/pkg/queue/queue_test.go
internal/pkg/queue/stats.go

Merge @yzqzss feature and make it optional, also use non-committed Index in tests.

Improve WAL concurrency performance by @yzqzss and make it optional

---

internal/pkg/queue/index/manager.go

fix: hanging on indexManager.Close()

---

internal/pkg/utils/url.go
internal/pkg/utils/url_test.go

This PR adds additional tests and removes unneeded calls when turning URLs into strings.

Add additional tests and validate current URL behavior

---

.github/workflows/build.yml
.github/workflows/go.yml
internal/pkg/crawl/config.go

Allows us to differentiate between crawls when searching

Add job and WARC prefix to pyroscope tags for better search

---

internal/pkg/crawl/worker_pool.go

Fix worker state panic when current item or URL is nil

---

internal/pkg/controler/pipeline.go
internal/pkg/controler/watchers/disk.go
internal/pkg/controler/watchers/disk_test.go

Check disk space before starting

---

internal/pkg/postprocessor/utils.go

Add missing status 303 "See Other"
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303
Refactor to make it more readable.

Improve isStatusCodeRedirect

---

internal/pkg/controler/pipeline.go

Fix panic when stopping unstarted API server

---

cmd/get.go
internal/pkg/archiver/archiver.go
internal/pkg/archiver/ratelimiter/adjust.go
internal/pkg/archiver/ratelimiter/manager.go
internal/pkg/archiver/ratelimiter/manager_test.go
internal/pkg/archiver/ratelimiter/ratelimiter.go
internal/pkg/archiver/ratelimiter/ratelimiter_test.go
internal/pkg/config/config.go
internal/pkg/postprocessor/assets.go
internal/pkg/postprocessor/extractor/html.go
internal/pkg/postprocessor/extractor/s3.go
internal/pkg/postprocessor/extractor/utils.go
internal/pkg/postprocessor/extractor/xml.go
internal/pkg/postprocessor/outlinks.go
internal/pkg/preprocessor/preprocessor.go

This package adds a token-based rate limiting system. It aims to limit the req/s allowed per host and adjust that rate based on archiver's feedback (status code).

Add ratelimiter package

---

README.md
go.mod
go.sum
internal/pkg/archiver/archiver.go
internal/pkg/archiver/body.go
internal/pkg/archiver/discard/discard.go
internal/pkg/archiver/warc.go
internal/pkg/postprocessor/extractor/s3_test.go
internal/pkg/postprocessor/extractor/xml_test.go
internal/pkg/postprocessor/sitespecific/ina/ina.go
internal/pkg/utils/version.go
pkg/models/url.go

update warc library package references

---

internal/pkg/postprocessor/extractor/xml.go

The original code loads all the doc in memory before parsing. This is slow and uses 2x memory than needed.
We drop `ReadAll` and pass the body to `xml.NewDecoder()`.

Optimise XML extractor document loading

---

cmd/get.go
internal/pkg/config/config.go
internal/pkg/postprocessor/extractor/html.go
internal/pkg/postprocessor/outlinks.go

This adds the `--strict-regex` toggle which is required to utilize the stricter regex setting.

Regex improvements and add strict regex toggle

---

internal/pkg/postprocessor/extractor/object_storage_azure_test.go

fix failed https://github.com/internetarchive/Zeno/actions/runs/15152201102 test

Make Azure test URLs insensitive to the order of the URL query parameters

---

internal/pkg/postprocessor/extractor/html.go
internal/pkg/postprocessor/extractor/html_test.go

Fix the nil `item.url.parsed` panic html test

---

internal/pkg/postprocessor/extractor/html.go
internal/pkg/postprocessor/extractor/html_test.go

Fixes #298
(recreated due to rebase issue)

Extract iframe SRC as outlinks

---

internal/pkg/archiver/ratelimiter/main_test.go
internal/pkg/controler/pause/main_test.go
internal/pkg/controler/watchers/main_test.go
internal/pkg/log/ringbuffer/main_test.go
internal/pkg/postprocessor/extractor/html_test.go
internal/pkg/postprocessor/extractor/main_test.go
internal/pkg/postprocessor/main_test.go
internal/pkg/preprocessor/main_test.go
internal/pkg/reactor/main_test.go
internal/pkg/source/hq/main_test.go
internal/pkg/stats/main_test.go
internal/pkg/utils/main_test.go
pkg/models/main_test.go

Fixing issue: https://github.com/internetarchive/Zeno/issues/329

Use goleak in all package tests

---

internal/pkg/log/fielded_logger.go

Noticed that the order of the prefix args output by multiple FieldedLoggers is random due to the natural of Go `map`. 
```log
| url archived component=archiver.archive worker_id=5
| url archived worker_id=4 component=archiver.archive
| url archived component=archiver.archive worker_id=3
| url archived component=archiver.archive worker_id=0
| url archived worker_id=1 component=archiver.archive
| url archived component=archiver.archive worker_id=2
| url archived worker_id=5 component=archiver.archive
| url archived component=archiver.archive worker_id=4
| url archived component=archiver.archive worker_id=3
...
```
This PR "fix" the order.

chore(FieldedLogger): log with odered prefix fileds

---

internal/pkg/archiver/archiver.go
internal/pkg/archiver/discard/README.md

Also added some notes about discard hooks.

Fix: discard hooks does not interrupt downloads

---

internal/pkg/archiver/archiver.go

bug: `--max-content-length` didn't work for those bad status responses before.
similar to #383

Fix: `BadStatusCode` responses are not handled by `copyWithTimeout()`

---

internal/pkg/postprocessor/assets.go
internal/pkg/postprocessor/assets_test.go
internal/pkg/postprocessor/item.go

Addressing issue https://github.com/internetarchive/Zeno/issues/397
Also add unit test.

Move reddit.com asset URL fix to SanitizeAssetsOutlinks

---

internal/pkg/consul/consul.go
internal/pkg/controler/pipeline.go
internal/pkg/controler/watchers/warc.go
internal/pkg/finisher/finisher.go
internal/pkg/postprocessor/postprocessor.go
internal/pkg/preprocessor/preprocessor.go
internal/pkg/reactor/reactor.go
internal/pkg/reactor/reactor_test.go

Reverts internetarchive/Zeno#435
---
Reason: https://github.com/internetarchive/Zeno/pull/435#issuecomment-3194039399

Revert "Create rootContext and share with components"

---

internal/pkg/controler/pause/pause_test.go

refactor `TestPauseResumeE2E` with synctest for accuracy
