internetarchive/Zeno

- internal/pkg/crawl/outlinks.go
Fragment or hash URLs almost always end up on the exact same page, especially ones without a full URL.
URLs like: "#main" or "#content" would be filtered out.
Important note: this won't filter out outlinks that contain fragment URLs if they are full URLs. (Maybe stripping out the fragments to allow proper seenchecking could make more sense in a future PR?)
> Filter out outlinks that being with a # (fragment or hash URL)

- internal/pkg/crawl/outlinks.go
- internal/pkg/utils/url.go
This entirely wipes out the "fragment" section from URLs, effectively removing them entirely from the outlinks. These are unwanted.
> fix: Properly remove fragments entirely from outlinks.

- internal/pkg/crawl/capture.go
- internal/pkg/crawl/outlinks.go
- internal/pkg/utils/url.go
Before, when the connection was not proxied, they weren't getting retried. This is the exact opposite of the expected behavior. With this change, we respect the MaxRetry and retry correctly to the limit while sending better logging messages than before. 
(Somewhat addresses #16 but I don't think this is exactly what I was looking into)
(I think this _might_ have a commit from another branch as well, my apologies.)
> Fix retry on non-proxied connections

- internal/pkg/crawl/capture.go
I made some improvements to retry on errors to ensure they don't immediately retry and cleaned up capture.go from the legacy markTempFileDone which isn't used.
> Code cleanup and some improvements

- internal/pkg/crawl/capture.go
- internal/pkg/utils/url.go
We got this error multiple times:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x63232b]
goroutine 82 [running]:
net/url.(*URL).ResolveReference(0x0, 0xc017ab3090, 0xc003b7ab70)
/home/corentin/.go/src/net/url/url.go:1077 +0x8b
github.com/CorentinB/Zeno/internal/pkg/utils.MakeAbsolute(0x0, 0xc000319200, 0xc, 0x10, 0x0, 0x0, 0x0)
/1/crawling/certificate-transparency/Zeno/internal/pkg/utils/url.go:15 +0xe5
github.com/CorentinB/Zeno/internal/pkg/crawl.extractOutlinks(0x0, 0xc010fd04b0, 0xc003b7a750, 0xc003b7a750, 0x0, 0x0, 0xc02f12ec00)
/1/crawling/certificate-transparency/Zeno/internal/pkg/crawl/outlinks.go:40 +0x26c
github.com/CorentinB/Zeno/internal/pkg/crawl.(*Crawl).Capture(0xc0001f2300, …
```
> Fix: potential SIGSEV when grabbing new base value from the base HTML tag

- cmd/cmd.go
- cmd/utils.go
- config/config.go
- go.mod
- go.sum
- internal/pkg/crawl/crawl.go
Add toggle for validating HTTPS certificates. By default this is set to "off" and we aren't validating certificates. Adding "--enable-cert-validation" will enable the functionality. 
Fixes #24
> Update warc to 0.8.8

- .gitignore
- cmd/all/all.go
- cmd/get/get.go
- cmd/get/hq.go
- cmd/get/list.go
- cmd/get/url.go
- cmd/version/deps.go
- cmd/version/version.go
- internal/pkg/crawl/crawl.go
- internal/pkg/crawl/utils.go
- internal/pkg/crawl/warc.go
- internal/pkg/utils/utils.go
- internal/pkg/utils/version.go
- main.go
Adds commit hash to warcinfo record, this is currently returning the entire hash, maybe we should return the first 7 characters like GitHub, which retains enough information to figure out exactly what code was writing to WARC? 
In warcinfo:
Current commit: `software: Zeno ae02086213b09b0a85388321596a99a1995e6ce2-true`
Previously: `software: Zeno`
Proposed additional, possible, change: `software: Zeno ae02086-true`
(and if nothing was modified in the local git tree: `software: Zeno ae02086`)
> Add real version number

- internal/pkg/crawl/capture.go
If a text/ (HTML or similar) is being crawled, but assets are disabled and max hops 0, there's no reason to use goquery and put it into memory. This should be slightly more efficient.
(Would appreciate a double check on the if statement)
> More efficient handling of text/ payloads if we aren't trying to scrape them

- go.mod
- go.sum
(Still investigating `https://www.tiktok.com/business/en-US`, but with the older version, 0.8.20, we seem to just get a 403 from Akamai anyways. I don't think we are missing any TLS extension support like last time and taking a look in wireshark, I can't immediately see any issues. 😢 )
> feat: update warc to 0.8.21

- internal/pkg/crawl/capture.go
- internal/pkg/crawl/utils.go
- internal/pkg/utils/utils.go
There was a special case where a worker could be blocked, if it were to follow more redirections than the number of available slots in the crawl pool (the max # of requests that can be done to a given host).
This PR fixes that.
> Fix potential blocking

- internal/pkg/frontier/save.go
- internal/pkg/frontier/utils.go
Resolves frontier saving issue. Has been tested briefly on my machine and appears to work correctly.
> Properly save sync.map version of Frontier

- .gitignore
- cmd/utils.go
- internal/pkg/crawl/api.go
- internal/pkg/crawl/capture.go
- internal/pkg/crawl/crawl.go
- internal/pkg/crawl/finish.go
- internal/pkg/crawl/worker.go
- Workers are now bound to a an operator-like structure, their state is visible and manipulated through that object
- Workers state is visible using API queries
- Worker state is observed by a routine ensuring consistency
This is the followup of #63 that was used to bring fork changes to the origin repo
> Add state management for workers

- internal/pkg/crawl/capture.go
- internal/pkg/crawl/sitespecific/facebook/facebook.go
This PR adds a site-specific code to archive embed URLs for Facebook.com posts URLs.
So when an URL like this https://www.facebook.com/ernest.lowe.10/posts/10159070254449221 is detected, it generates the post.php embed URL and archive it: https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fernest.lowe.10%2Fposts%2F10159070254449221&show_text=true
> Add site-specific code for Facebook

- cmd/utils.go
- internal/pkg/crawl/capture.go
Prometheus was always expecting to be present but API is not always set when crawls are ran, resulting in Prometheus not being correctly defined. This resolves that issue.
> Fix crash when --api is not set

- .gitignore
- internal/pkg/crawl/finish.go
- internal/pkg/crawl/stats.go
- internal/pkg/crawl/worker.go
- internal/pkg/queue/access.go
- internal/pkg/queue/access_test.go
- internal/pkg/queue/dequeue.go
- internal/pkg/queue/enqueue.go
- internal/pkg/queue/metadata.go
- internal/pkg/queue/queue.go
- internal/pkg/queue/queue_test.go
The goal here is to distribute hosts to dequeue from to each worker to avoid repeatedly hitting the same domain while crawling thus avoiding any rate-limiting and ventilate the RPS as much as possible between different hosts
The task was to find an efficient method for distributing numbers (`i` for `hosts[i]`) within an interval `[0,len(hosts)]` that can change over time, based on an atomic uint64 counter that increments with each iteration (dequeue). The goal was to achieve a uniform distribution while maintaining high performance.
To facilitate understanding we will name the atomic uint64 counter : `x` and the interval : `y`
1. Perfect coverage of the interval
2. Low execution time
3. Uniformity of distribution
We implemented and tested eight different distribution methods:
1. Simple …
> Implement host rotation and Enqueue/Dequeue access regulation via atomic booleans

- internal/pkg/crawl/worker.go
- internal/pkg/queue/enqueue.go
- internal/pkg/queue/handover.go
- internal/pkg/queue/queue.go
We've implemented a new "handover" mechanism to optimize item processing in our high-performance crawling system. Here's how it works:
1. When new items are received, we attempt an immediate handover to available workers before enqueueing.
2. We use a buffered channel (HandoverChannel) with a capacity of 1 for this purpose.
3. The process loops through each item in a batch:  
- If the handover channel is empty, we put the item in for immediate processing.
- If the channel is full, we encode then batch the item for later enqueueing.
4. After processing all items, we check if an item is still in the handover channel. If so, we move it out of the handover channel and encode then batch for enqueueing.
This approach prioritizes immediate processing when workers are available, minimizing …
> Have `queue.Enqueue()` handover items to idle workers and optimize workers routines

- go.mod
- go.sum
- internal/pkg/crawl/capture.go
- internal/pkg/crawl/link_header.go
- internal/pkg/crawl/link_header_test.go
This PR adds a Parse function for linkheader parsing, therefore removing the dependency on `github.com/tomnomnom/linkheader`. This also includes writing unit tests for the function
Closes #85
> Implement linkheader parsing

- internal/pkg/crawl/worker.go
revert #101
Do not use `runtime.Gosched()` in loop, which will spinning your CPUs time for endless coroutine context switching. It won't magically turn polling into blocking.
In addition, Golang's coroutines are preemptive since Go1.14. There will be no starving coroutines, we don't need to manually call `runtime.Gosched()` nowadays.
> Remove `runtime.Gosched()` in polling

- cmd/get.go
- config/config.go
- internal/pkg/crawl/api.go
- internal/pkg/crawl/config.go
- internal/pkg/crawl/crawl.go
- internal/pkg/crawl/hq.go
- internal/pkg/crawl/stats.go
- internal/pkg/crawl/worker.go
- internal/pkg/crawl/worker_pool.go
- internal/pkg/queue/access_test.go
- internal/pkg/queue/dequeue.go
- internal/pkg/queue/dequeue_test.go
- internal/pkg/queue/enqueue.go
- internal/pkg/queue/enqueue_test.go
- internal/pkg/queue/handover.go
- internal/pkg/queue/handover_test.go
- internal/pkg/queue/queue.go
- internal/pkg/queue/queue_test.go
- internal/pkg/queue/stats.go
Add :
- make handover optional
- added lastAction on API worker state to troubleshoot
- made the default HQ batches smaller
- made handover hold the whole batch before enqueuing on disk
- handover now has an automatic closing mechanism that adapts to activity so the handover get closed and drained on disk if no workers need it
> Queue handover v2

- internal/pkg/crawl/worker.go
- internal/pkg/queue/enqueue_test.go
- internal/pkg/queue/metadata.go
- internal/pkg/queue/queue.go
- internal/pkg/queue/stats.go
- remove HostDistribution and TopHosts stats
`genStats()` takes too much time to generate HostDistribution and TopHosts.
Let's remove them until we find a better statistics implementation. :disappointed:
> Calming down queue stats

- cmd/get.go
- internal/pkg/queue/enqueue.go
- internal/pkg/queue/index/manager.go
- internal/pkg/queue/index/manager_test.go
- internal/pkg/queue/index/recovery_test.go
- internal/pkg/queue/queue_test.go
- Make batchEnqueueUntilCommitted release the mutex lock before executing AwaitWALCommitted so that multiple batchEnqueueUntilCommitted can be executed concurrently with/like enqueueUntilCommitted.
- try to use a fixed fsync interval (currently hardcoded 100ms) to achieve smoother queue performance.
> Lock-free AwaitWALCommitted (and smoother queue?)

- internal/pkg/crawl/hq.go
the returned payload from HQ only contain new URL(s) to be crawled by Zeno.
> fix: `HQSeencheckURL()` incorrectly distinguishes between new and old URL

- internal/pkg/crawl/extractor/xml.go
This PR replaces `github.com/clbanning/mxj/v2` and uses `encoding/xml` `xml.Decoder` to parse xml and extract urls within.
EDIT: All tests pass now. The PR is complete
Co-Author: @yzqzss 
<strike>
Only two tests fail, I am trying to fix those
<details>
<summary>Tests</summary>
```fish
go: downloading git.archive.org/wb/gocrawlhq v1.2.13
internal/pkg/crawl/config.go:11:2: unrecognized import path "git.archive.org/wb/gocrawlhq": https fetch: Get "https://git.archive.org/wb/gocrawlhq?go-get=1": dial tcp 207.241.235.124:443: i/o timeout
=== RUN   TestJSON
=== RUN   TestJSON/Valid_JSON_with_URLs
=== RUN   TestJSON/Invalid_JSON
=== RUN   TestJSON/JSON_with_no_URLs
=== RUN   TestJSON/JSON_with_URLs_in_various_fields
=== RUN   TestJSON/JSON_with_array_of_URLs
--- PASS: TestJSON (0.00s)
--- PASS: …
```
> Implement XML parsing using stdlib

- internal/pkg/crawl/capture.go
- internal/pkg/crawl/extractor/xml.go
- internal/pkg/crawl/extractor/xml_test.go
~~This PR is based on #155~~
---
- Introduce lax parsing mode, so that we can get URLs from unbalanced or malformed XML.
- Return parsed `URLs` instead of `nil` when an error occurs.
- Replace `TestXMLBodyReadError` test with `TestXMLBodySyntaxEOFError`.
> Better xml parsing

- go.mod
- go.sum
- internal/pkg/config/config.go
- internal/pkg/postprocessor/assets.go
- internal/pkg/postprocessor/extractor/base.go
- internal/pkg/postprocessor/extractor/html.go
- internal/pkg/postprocessor/outlinks.go
- internal/pkg/postprocessor/postprocess.go
- internal/pkg/postprocessor/postprocessor.go
- internal/pkg/preprocessor/preprocessor.go
- pkg/models/url.go
This PR aims to implement the same mechanism that is being used for WARC writing, for the post-processing of response body. That is, when reaching a certain threshold of size (2MB right now), the response body of a request that need to be post-processed is rolled over to a file on disk.
> Reduce memory usage by using spooled temp file

- internal/pkg/postprocessor/postprocess.go
- pkg/models/item.go
- pkg/models/item_test.go
This PR aims to make use of tree depth instead of hops for stopping the extraction of assets. (but still allowing 2 layers of extraction)
> Fix assets hops handling

- internal/pkg/postprocessor/assets.go
- internal/pkg/postprocessor/extractor/json.go
- internal/pkg/postprocessor/extractor/json_test.go
- internal/pkg/postprocessor/extractor/utils.go
- internal/pkg/postprocessor/extractor/utils_test.go
- internal/pkg/postprocessor/extractor/xml.go
- internal/pkg/postprocessor/extractor/xml_test.go
- internal/pkg/postprocessor/item.go
- internal/pkg/postprocessor/outlinks.go
- internal/pkg/postprocessor/sitespecific/truthsocial/truthsocial.go
This PR adds a check when doing JSON & XML extraction of assets to verify that the URLs we extract are indeed files and not "pages". URLs that do not pass the test are returned as outlinks to be (potentially) queued back.
> Better JSON/XML extraction

- internal/pkg/postprocessor/extractor/base.go
- internal/pkg/postprocessor/extractor/base_test.go
The current code looks for `base` tag but doesn't stop if it finds one. It will still search until the end of the doc.
The suggested improvement uses `doc.Find("base").First()` to get just the first element as `<base>` is used just once on the HTML doc header.
We also add a unit test.
> Optimise extractBaseTag and add unit test

- internal/pkg/postprocessor/extractor/html.go
- internal/pkg/postprocessor/extractor/html_test.go
Group video[src] and audio[src] selections in the same `goquery.Find` query because their handling is identical.
Group scanning all doc element for attributes `[data-item], [style], [data-preview]` in the same `goquery.Find` query.
The previous query `goquery.Find('*')` was returning all elements and then we checked for specific attributes.
The new query returns only the elements which have one of the specified attributes, so it should be much faster.
Add unit tests to validate the suggested improvements.
> Refactor HTMLAssets and add unit tests

- internal/pkg/archiver/archiver.go
- internal/pkg/controler/channels.go
- internal/pkg/controler/pipeline.go
- internal/pkg/finisher/finisher.go
- internal/pkg/postprocessor/postprocessor.go
- internal/pkg/preprocessor/preprocessor.go
- internal/pkg/stats/methods.go
- internal/pkg/stats/stats.go
This PR itself serves as a point of centralization for every concurrency rework PR. This shouldn't be reviewed, upstream PR should be.
Every stage is reworked to use the classic fan-in/fan-out concurrency model instead of the dynamic one we made at the start which might be causing deadlocks and fatigue on the system.
> Rework concurrency for pipeline stages

- internal/pkg/controler/pipeline.go
- internal/pkg/postprocessor/extractor/base_test.go
- internal/pkg/postprocessor/extractor/html_test.go
- internal/pkg/postprocessor/extractor/resolve_test.go
- internal/pkg/postprocessor/item.go
- internal/pkg/reactor/reactor_test.go
- internal/pkg/source/hq/consumer.go
- pkg/models/item.go
- pkg/models/item_dedupe.go
- pkg/models/item_dedupe_test.go
- pkg/models/item_misc_test.go
- pkg/models/item_test.go
Item.seed is redundant because we already have the parent attribute. (When parent == nil, then the item is a seed).
Fixing issue: https://github.com/internetarchive/Zeno/issues/221
> Drop item.seed attribute

- internal/pkg/archiver/archiver.go
- internal/pkg/archiver/warc.go
- internal/pkg/controler/pipeline.go
- internal/pkg/controler/watchers/warc.go
- Removed the `archiver` local WARC Writing queue watcher in benefit of `controler/watchers` one
- Made the `controler/watchers` WARC WQ watcher also update stats
- Made the `controler/watchers` WARC WQ watcher respect a timeout for unpausing to avoid pausing and unpausing too fast under high contention
- Optimized `if` statements in `controler/watchers` WARC WQ watcher to avoid computing values when not needed (put bool check as first condition)
> Revamp WARC writing queue watcher

- internal/pkg/archiver/body.go
- internal/pkg/postprocessor/extractor/testdata/rss2.0.xml
- internal/pkg/postprocessor/extractor/xml.go
- internal/pkg/postprocessor/extractor/xml_test.go
- internal/pkg/utils/mimetype.go
XML RSS is just XML; the only thing preventing Zeno post-processing for XML RSS is its mimetype.Parent().String() != "text/plain".
https://github.com/internetarchive/Zeno/blob/f004ca45ea0a06d6958d21be919f5b8ca34ddb80/internal/pkg/archiver/body.go#L46-L47
General XML mimetype:
"text/xml; charset=utf-8" -> "text/plain" -> "application/octet-stream"
`u.GetMIMEType().Parent().String() == "text/plain"` is `true`
XML RSS mimetype:
"application/rss+xml" -> "text/xml" -> "text/plain" -> "application/octet-stream"
`u.GetMIMEType().Parent().String() == "text/plain"` is `false`
---
To address this, I added `IsMIMETypeInHierarchy()` to recursively check if the MIME type and its parents match the expected MIME type.
close: #159
> Extract RSS XML as general XML

- internal/pkg/postprocessor/extractor/base.go
- internal/pkg/postprocessor/extractor/base_test.go
- internal/pkg/postprocessor/extractor/html.go
- internal/pkg/postprocessor/extractor/resolve.go
- internal/pkg/postprocessor/extractor/resolve_test.go
- pkg/models/item.go
- Enhance `extractBaseTag()` function to conform with whatwg's spec: <https://html.spec.whatwg.org/multipage/semantics.html#the-base-element>
- Change base URL type in Item model from `string` to `*url.URL` for convenience.
- Make `HTMLAssets()` resolve URLs directly in `html.go`, just like `HTMLOutlinks()`.
> Enhance base URL handling

- internal/pkg/archiver/body.go
As suggested by the author of the library for better results. https://github.com/gabriel-vasile/mimetype/blob/66e5c005d80684b64f47eeeb15ad439ee6fad667/mimetype.go#L15
It used to be 2k but they increased it to 3k recently.
> Increase mimetype detection buffer from 2k to 3k

- internal/pkg/postprocessor/extractor/pdf.go
- internal/pkg/postprocessor/outlinks.go
- internal/pkg/postprocessor/outlinks_test.go
We filtered some protocols only in the PDF outlink extractor. We didn't catch uppercase and we were missing a lot of protocols.
We implement a common filter function that applies to all extractors and remove the PDF specific code.
We also add a unit test.
> Filter outlinks with unwanted protocols

- internal/pkg/postprocessor/extractor/object_storage.go
- internal/pkg/postprocessor/extractor/object_storage_azure.go
- internal/pkg/postprocessor/extractor/object_storage_azure_test.go
- internal/pkg/postprocessor/extractor/object_storage_s3.go
- internal/pkg/postprocessor/extractor/object_storage_s3_test.go
- internal/pkg/postprocessor/extractor/object_storage_test.go
- internal/pkg/postprocessor/extractor/utils.go
- internal/pkg/postprocessor/outlinks.go
When fixing #280, I found that Azure Blob is not S3 compatible, so I implemented a separate Azure sub-extractor. Then I thought that one URL can obviously only be one type of OSS, so I created the `ObjectStorage()` method to call the sub-extractor (S3/Azure/...) conditionally.
> Optimize the OSS extraction process and implement Azure Blob extractor

- cmd/cmd.go
- go.mod
- go.sum
- internal/pkg/config/config.go
- internal/pkg/log/config.go
- internal/pkg/log/fielded_logger.go
Now my eyes can easily spot the warn/error logs from the terminal stream.
Also added --no-color-logs flag to disable this feature. (to switch back to [slog] handler)
---
This PR only colors the stdout and stderr terminal logging handlers and does not affect the file logging handler (`/jobs/{job}/log/ZENO-{time}.log`).
---
The [slogcolor] handler's output format is slightly different from slog. For example, it does not escape the `"` to `\"` in the log message.
---
Introduced lib:
- https://github.com/MatusOllah/slogcolor
> Make terminal logging colorful 🌈

- internal/pkg/stats/methods.go
- internal/pkg/stats/stats.go
Also, add two missing stats to `GetMapTUI()` outputs.
> Cleanup unused stats methods

- internal/pkg/controler/pipeline.go
- internal/pkg/postprocessor/extractor/base_test.go
- internal/pkg/postprocessor/extractor/html_test.go
- internal/pkg/postprocessor/extractor/resolve_test.go
- internal/pkg/postprocessor/item.go
- internal/pkg/preprocessor/exclusion_test.go
- internal/pkg/reactor/reactor_test.go
- internal/pkg/source/hq/consumer.go
- internal/pkg/source/lq/consumer.go
- pkg/models/item.go
- pkg/models/item_test.go
Rename `models.NewItem` to `models.NewItemWithID`.
Create `models.NewItem(URL *URL, seedVia string)` which uses `uuid.New().String()` internally to define the `id`.
This way, the code becomes much cleaner.
> Simplify models.NewItem

- internal/pkg/archiver/archiver.go
- internal/pkg/postprocessor/extractor/html.go
- internal/pkg/postprocessor/outlinks.go
- internal/pkg/preprocessor/preprocessor.go
`pkg.model.URL` has `String()` method which means that it is invoked automatically when you log it. There is no need to call `.String()`.
`net/url` also supports the same.
> Simplify URL logging

- internal/pkg/postprocessor/item.go
- internal/pkg/postprocessor/postprocessor.go
- pkg/models/item.go
`closeBody` is a function about the internal state of the `Item`. It makes sense to put it in `pkg.models.item` and use it as `Item.Close()`. Its better to have all the `Item` related methods in one place in `pkg.models.Item` instead of having them spread in preprocessor / postprocessor code.
> Move closeBody(seed *model.Item) to Item.Close()

- internal/pkg/postprocessor/extractor/css.go
- internal/pkg/postprocessor/extractor/css_test.go
- internal/pkg/postprocessor/extractor/html.go
#323
close: #296 
This PR adds the ability to extract `@import` urls at the css extractor level.
---
Crawling and archiving these `@import` urls will be implemented in the next PR.
> Extracting URLs from CSS `@import` rule

- internal/pkg/postprocessor/assets.go
- internal/pkg/postprocessor/extractor/html.go
- internal/pkg/postprocessor/extractor/json.go
- internal/pkg/postprocessor/extractor/json_test.go
- internal/pkg/postprocessor/extractor/utils.go
- internal/pkg/postprocessor/extractor/utils_test.go
- internal/pkg/postprocessor/extractor/xml_test.go
- internal/pkg/postprocessor/outlinks.go
- internal/pkg/postprocessor/sitespecific/github/github.go
- internal/pkg/postprocessor/sitespecific/github/github_test.go
- internal/pkg/postprocessor/utils.go
Improved the archiving quality of GitHub Issue&PR pages.
26e6dd2ad74420cea746b3b87449fccbf58c8a10, f94197f5947a1030422e86256e398d4f18467af0 fix:
I noticed that some "data:" URLs were being queued that should have been filtered => We forgot to call `filterURLsByProtocol()` for assets.
e543bb3cd6149f060f2a2eb39034e9b0c15a10b0 fix:
GitHub has rewritten the issue pages in react in recent months. Now they embed many useful (images, videos, user avatars...) assets into HTML `<script>` tags as JSON for issue pages.
These assets are in JSON strings.
and JSON extractor currently only considers an asset if the entire string is a valid URL.
49de5c7e086a34b2ed81ba6581a8fe526069483b improved:
These GitHub assets have no file suffix, so a `sitespecific/github.go` patch was added to JSON extractor to …
> Improve GitHub archiving

- internal/pkg/config/config.go
I searched through the config struct found in ```pkg/config/config.go``` to see if any parameters were defined in the struct but *not* used anywhere else in the codebase, I could only find one parameter that was not used anywhere else.
I'm new to this project (hello) as well as go, so I will not take offense if this PR is not good at all. Just trying to help! :)
resolves #213 
Thanks
> removed unused config parameters

- internal/pkg/postprocessor/domainscrawl/domainscrawl.go
This code checks if `globalMatcher.enabled` is false and it sets it to true. This means that `globalMatcher.enabled` should be always just true.
> Remove redundant code in domainscrawl

- internal/pkg/controler/pipeline.go
- internal/pkg/preprocessor/preprocessor.go
- internal/pkg/source/hq/consumer.go
- internal/pkg/source/hq/finisher.go
- internal/pkg/source/hq/hq.go
- internal/pkg/source/hq/producer.go
- internal/pkg/source/hq/seencheck.go
- internal/pkg/source/hq/websocket.go
- internal/pkg/source/lq/client.go
- internal/pkg/source/lq/consumer.go
- internal/pkg/source/lq/finisher.go
- internal/pkg/source/lq/lq.go
- internal/pkg/source/lq/producer.go
- internal/pkg/source/source.go
Most is said in the title.
What has been done :
- got rid of `source/hq` and `source/lq` global pointers
- `source/hq` and `source/lq` functions now work as methods and references are held if needed
- `preprocessor` now has a function to set a seencheck function, it is set at the `controler` and retains the same properties as before
> Implement a shared interface for `source` so anyone can implement their own source of items

- go.mod
- go.sum
Makes sense to bump in the interim even if we eventually end up proceeding with #374
> chore(deps): update github.com/ada-url/goada to v1.0.0

- internal/pkg/preprocessor/preprocessor.go
- internal/pkg/preprocessor/sitespecific/npr/npr.go
- internal/pkg/preprocessor/sitespecific/reddit/reddit.go
- internal/pkg/preprocessor/sitespecific/sitespecific.go
- internal/pkg/preprocessor/sitespecific/sitespecific_test.go
- internal/pkg/preprocessor/sitespecific/tiktok/tiktok.go
- internal/pkg/preprocessor/sitespecific/truthsocial/truthsocial.go
Use a common Go interface. All preprocessors must implement `Match` and `Apply` methods. Rename the older arbitrary method names and use the interface.
Simplify calling sitespecific preprocessors to just `sitespecific.RunPreprocessors`.
Now, it is much simpler to define a new site specific preprocessor.
Add unit tests.
> Refactor request preprocessors

- internal/pkg/postprocessor/item.go
- pkg/models/item.go
Placing `SetDocument(nil)` in the end of the method doesn't guarantee that it will be always executed. If the method returns early, it is skipped and memory isn't freed.
`Item` has a `Close()` method. Conceptually its better to include memory cleanup in `Item.Close`.
Also, method `postprocessItem` includes `defer item.Close()`.
So, it makes sense to move `SetDocument(nil)` in there.
> Move SetDocument(nil) to Item.Close

- internal/pkg/postprocessor/extractor/base.go
- internal/pkg/postprocessor/extractor/base_test.go
- internal/pkg/postprocessor/extractor/html.go
- internal/pkg/postprocessor/extractor/html_test.go
- internal/pkg/postprocessor/extractor/resolve.go
- internal/pkg/postprocessor/extractor/resolve_test.go
- internal/pkg/postprocessor/outlinks.go
- pkg/models/item.go
- pkg/models/url.go
We need all outlink extractors to use the same inputs / outputs for better code organization and correctness.
Without this change, we can't use Go interfaces.
Modify `HTMLOutlinks` extractor to use `models.URL` instead of `models.Item`.
Move the `base` attribute and related `GetBase`, `SetBase` methods from `Item` to `URL`. This also makes sense as the base URL attribute is more related to the `URL` object.
Modify `resolveURL` extractor to use `models.URL` instead of `models.Item`.
Modify `extractBaseTag` extractor to use `models.URL` instead of `models.Item`.
> Refactor HTMLOutlinks to use models.URL instead of models.Item

- internal/pkg/postprocessor/assets.go
- internal/pkg/postprocessor/assets_test.go
- internal/pkg/postprocessor/item.go
Rename `ExtractAssets` to `ExtractAssetsOutlinks` because the function
returns assets and potentially outlinks. The original name was
confusing.
Split `ExtractAssetsOutlinks` into 2 functions: `Extractors` and
`SanitizeAssetsOutlinks`.
The sanitization function now runs for all extractor output, earlier it
didn't run when an error occured. See issue:
https://github.com/internetarchive/Zeno/issues/396
Add unit test for `SanitizeAssetsOutlinks`.
> Refactor ExtractAssets

- internal/pkg/postprocessor/extractor/html.go
Define `url` and `item` once on logger init instead of calling them on each `Warn` and `Debug` call.
> Simplify HTML extractor logging

- internal/pkg/config/config.go
- internal/pkg/postprocessor/outlinks.go
- internal/pkg/postprocessor/outlinks_test.go
It is useful to be able to set a limit to the number of outlinks you extract.
Add relevant unit test.
> Add max outlinks option

- internal/pkg/stats/rate_bucket.go
Locking is slowing us down, this seems like a good case for `sync.Map`.
> Use sync.Map in RateBucket instead of manual locking

- internal/pkg/postprocessor/assets.go
- internal/pkg/postprocessor/item.go
Define `item_id` once on logger init instead of calling it on each logger call.
> Simplify postprocessor logging

- internal/pkg/archiver/archiver.go
- internal/pkg/postprocessor/postprocessor.go
- internal/pkg/preprocessor/preprocessor.go
- internal/pkg/source/hq/hq.go
- internal/pkg/source/lq/lq.go
We keep `stats.Init()` in the pipeline where all components are initialized and remove every other `stats.Init()` call.
Using `stats.Init()` multiple times doesn't have any effect since it uses `sync.Once` to run stats init only once.
> Remove multiple redundant stats.Init()

- cmd/get.go
- go.mod
- internal/pkg/archiver/archiver.go
- internal/pkg/config/config.go
- internal/pkg/config/exclusions.go
- internal/pkg/log/log.go
- internal/pkg/preprocessor/preprocessor.go
This PR adds the capability to "live reload" the exclusion files.
It is off by default, I would like the opposite but I didn't want to implement a breaking change, we can discuss it if someone thinks it should be on by default.
There is a new setting `--exclusion-file-live-reload` to enable it, by default it reloads the files every 60 seconds, but this can be changed with `--exclusion-file-live-reload-interval` which takes a int corresponding to the number of seconds between each reload.
It works with both file on disk, and remotely. It's a very simple implementation, there are ways we could make it more efficient, it will certainly come in a future PR when I have more time to allow to it.
> Add live reload of exclusion lists (and switch to go 1.25)

- internal/pkg/archiver/ratelimiter/manager_test.go
- internal/pkg/archiver/ratelimiter/ratelimiter_test.go
- internal/pkg/controler/pause/pause.go
- internal/pkg/controler/pause/pause_test.go
- internal/pkg/controler/watchers/warc.go
- internal/pkg/log/ringbuffer/ringbuffer.go
- internal/pkg/log/ringbuffer/ringbuffer_test.go
- internal/pkg/postprocessor/extractor/css_test.go
- internal/pkg/postprocessor/extractor/html.go
- internal/pkg/postprocessor/extractor/json.go
- internal/pkg/postprocessor/extractor/link_header.go
- internal/pkg/postprocessor/extractor/link_header_test.go
- internal/pkg/postprocessor/extractor/xml_test.go
- internal/pkg/postprocessor/outlinks_test.go
- internal/pkg/postprocessor/sitespecific/ina/ina.go
- internal/pkg/reactor/reactor_test.go
- internal/pkg/reactor/state.go
- internal/pkg/stats/rate_test.go
- internal/pkg/stats/stats.go
- internal/pkg/ui/pause.go
- internal/pkg/ui/stats.go
- pkg/models/item.go
- pkg/models/item_test.go
- pkg/models/url_test.go
Well it's quite a vague title but I basically just ran `go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...`.
> Modernize code

- internal/pkg/consul/consul.go
- internal/pkg/controler/pipeline.go
- internal/pkg/controler/watchers/warc.go
- internal/pkg/finisher/finisher.go
- internal/pkg/postprocessor/postprocessor.go
- internal/pkg/preprocessor/preprocessor.go
- internal/pkg/reactor/reactor.go
- internal/pkg/reactor/reactor_test.go
Its not a good practice to create a separate context for each component without any special reasons.
We refactor to create a `rootContext` in `pipeline.Start` and pass it to many components.
One initial benefit of this approach is that you don't need to call `cancel()` in the "Stop" function of all components.
E.g. `consul.Stop()` is dropped because it isn't needed at all.
Now, `rootContextCancel()` is called in `pipeline.Stop` and all components using the `rootContext` are notified.
> Create rootContext and share with components

- cmd/cmd.go
- e2e/e2e.go
- e2e/test/cloudflare204/cloudflare204_test.go
- e2e/test/nonutf8encoding/contenttype/contenttype_test.go
- e2e/test/nonutf8encoding/metacharset/metacharset_test.go
- e2e/test/nxdomain/nxdomain_test.go
- internal/pkg/config/config.go
- internal/pkg/controler/signal.go
- internal/pkg/log/config.go
- internal/pkg/log/log.go
It suddenly occurred to me that the e2e test suite runs in the same package as Zeno. I don't need to mess around with sockets to get them communicating.
So I replaced the socket logging file with a `net.Pipe()` and then exposed Zeno's `SignalChannel` to the e2e suite.
> refactor(test): replace the socket logging with `net.Pipe()`

- internal/pkg/source/hq/websocket.go
Our HQ sends confirmation messages after `identify` messages. This should follow that format and ensure we are not spamming the log with unneeded messages. 
@yzqzss please let me know if this works for you as well!
> Add support for confirmed messages through WS

- internal/pkg/controler/pipeline.go
- internal/pkg/source/hq/hq.go
- internal/pkg/source/hq/websocket.go
Pass `HQKey, HQSecret, HQProject, HQAddress` as params on `HQ.New` instead of loading them via `config.Get()` inside `HQ.Start`.
This way, we can have multiple HQ client instances with different parameters.
This is necessary to be able to create a 2nd HQ client instance which connects an "outlinks" HQ project to send outlinks there.
> More versatile HQ client init

- internal/pkg/postprocessor/domainscrawl/domainscrawl.go
- internal/pkg/postprocessor/domainscrawl/domainscrawl_test.go
This pull request refactors the domainscrawl matcher in `internal/pkg/postprocessor/domainscrawl/domainscrawl.go` to improve testability and encapsulation. The matcher logic is moved from global functions and variables to instance methods on a new `matchEngine` type, and the tests are updated to use matcher instances instead of global state. This makes the codebase more modular and easier to test in isolation.
Matcher encapsulation and API changes:
* Introduced a `matchEngine` type and moved matcher logic from global functions to instance methods (e.g., `AddElements`, `Match`, `Reset`, `Enabled`). Added a `NewMatcher` constructor for creating isolated matcher instances. (`internal/pkg/postprocessor/domainscrawl/domainscrawl.go`)
* Updated the matcher API so that all matcher operations …
> Fix domainscrawl race in tests

- Dockerfile
Upgrades version of Go used in Dockerfile, fixing a failure caused while building container images: 
```
[1/2] STEP 6/8: RUN go mod download
go: go.mod requires go >= 1.25.1 (running go 1.24.3; GOTOOLCHAIN=local)
subprocess exited with status 1
```
> fix(docker): upgrades go version to 1.25.1

- pkg/models/item.go
- pkg/models/item_test.go
Previously, when we had an item error we returned `fmt.Errorf("item is fresh but has children")`. and then in the unit tests we had to use
`expected: errors.New("item is fresh but has children"`
There is no need to define an error multiple times. We define:
```
ErrItemFreshHasChildren = errors.New("item is fresh but has children")
```
and then use `ErrItemFreshHasChildren` everywhere.
This way, we can easily change the error text in one place and avoid breaking the unit tests.
Also, we could avoid doing error string comparison and use `errors.Is` but we can't do it right now because the tests have some special error cases and its not straightforward.
> Refactor item errors

- internal/pkg/postprocessor/extractor/html_document.go
- internal/pkg/postprocessor/extractor/html_document_test.go
Two optimisations:
We iterate query `key` -> `values` and then iterate each `value` in `values`. We encoded the `key` again and again for each `value`. We only need to do it once. We move the key encoding code outside the `values` loop.
We define `enc.NewEncoder().String()` every time we need to encode a value. We can define `encoder := enc.NewEncoder()` in the beginning and reuse it.
We add a unit test for a bad URL just to be sure.
> Optimise encodeNonUTF8QueryURLs

- internal/pkg/source/hq/consumer.go
- internal/pkg/source/hq/finisher.go
- internal/pkg/source/hq/hq.go
- internal/pkg/source/hq/producer.go
- internal/pkg/source/hq/seencheck.go
- internal/pkg/source/lq/consumer.go
- internal/pkg/source/lq/finisher.go
- internal/pkg/source/lq/lq.go
Note that we leave `context.TODO()` in `internal/pkg/source/hq/consumer.go` because its a special case.
Fixing issue: https://github.com/internetarchive/Zeno/issues/472
> Replace context.TODO() with the current component's context

- internal/pkg/preprocessor/preprocessor.go
- internal/pkg/preprocessor/seencheck/seencheck.go
Make `seencheck.isSeen` return error instead of `panic(err)`.
Make `SeencheckItem` return `err` instead of `panic(err)`.
`preprocess` should return `err` from `GlobalPreprocessor.Seenchecker` instead of just logging it.
If `preprocess` return an error, the program stops with `panic` so we have exactly the same program behavior as before but with better error handling and logging.
Also, the seencheck code is now much more cleaner and testable.
Relevant issue: https://github.com/internetarchive/Zeno/issues/473
> Drop panic from preprocessor seencheck

- internal/pkg/config/config.go
Config already returns errors and terminates when there is an issue. There is no need to use `os.Exit(1)` for these specific cases, return error and the program will terminate anyway where `config.InitConfig` is invoked if it gets an error.
Relevant to: https://github.com/internetarchive/Zeno/issues/473
> Return errors in config init instead of os.Exit
